### ISSUE TITLE
Language navigation should be context aware

### ISSUE THREAD

**Issue by mhaack** [Netcentric/cn-website#103]
Currently the links of the language navigation are hardcoded to the english and german homepages but they should consider the current page as context. For example when serving on https://www.netcentric.biz/what-we-do the "DE" link in the header should point to https://www.netcentric.biz/de/what-we-do.html and vice versa.

**Comment by NCalexiaeche** [comment]
fixed by https://github.com/Netcentric/cn-website/pull/239
