### ISSUE TITLE
Check caching strategy and performance of article loading

### ISSUE THREAD

**Issue by nc-andreashaller** [Netcentric/cn-website#108]
See https://github.com/hlxsites/netcentric/pull/93/files#r1033235092

**Comment by verlok-cn** [comment]
Hey @nc-andreashaller sorry I missed this, I will check.

**Comment by nc-andreashaller** [comment]
see the comment in https://github.com/hlxsites/netcentric/pull/93/files#r1033235092, the `getArticles` call is potentially done multiple times, the JavaScript the comment refers to is loaded for the Blog Post block which is to my knowledge loaded on all blog articles like https://www.netcentric.biz/insights/2022/12/collecting-the-right-data-to-deliver-personalized-experiences

**Comment by verlok-cn** [comment]
I have checked, it is always loaded from disk cache, so no optimisation required.

<img width="960" alt="Screenshot 2022-12-23 at 18 01 26" src="https://user-images.githubusercontent.com/119036844/209373563-6def577f-f38b-42c4-ab82-15ee009d36a7.png">
