### ISSUE TITLE
Footer alignment of social icons difference between new & old

### ISSUE THREAD

**Issue by mhaack** [Netcentric/cn-website#163]
EN current version:
![Screenshot 2022-12-01 at 17 17 07](https://user-images.githubusercontent.com/2643450/205104792-0596eeab-6b6c-49f6-8e40-e80473b66bf4.png)

old (screenshot from DE page):
![Screenshot 2022-12-01 at 17 16 59](https://user-images.githubusercontent.com/2643450/205104817-daff7b0a-1ea6-4e65-bc35-588b616c0203.png)

**Comment by NCalexiaeche** [comment]
This is related to the marketo form so it can be closed
