### ISSUE TITLE
Correct / improved 404 handling

### ISSUE THREAD

**Issue by mhaack** [Netcentric/cn-website#179]
Review the current approach of redirecting to homepage instead of display a 404 page.

**Comment by NCalexiaeche** [comment]
Can you check if this is still happening please @EduNCgit ?

**Comment by nc-andreashaller** [comment]
it is, what Markus meant with this ticket is that https://www.netcentric.biz/does-not-exist is redirecting to the homepage instead of showing a 404 page.
