### ISSUE TITLE
Implement reduces header & footer for campaign pages

### ISSUE THREAD

**Issue by mhaack** [Netcentric/cn-website#184]
Some campaign pages (on the old AEM site) have reduced header and footer

- [x] introduce "campaign" template for pages and switch in header & footer loading campaign specific header & footer doc
- [x] create "nav-campaign" doc with logo only
- [x] create reduced "footer-campaign" doc

**Comment by NCalexiaeche** [comment]
Hi @EduNCgit can you please check on Author which are the pages with a different footer (ie. bigger logo & less social media links) and list the URLs in here so we can double check if we need to add a specific thing for some targeted marketing campaign pages

**Comment by NCalexiaeche** [comment]
Should we close this ticket @mhaack  as this should be handle by the https://github.com/Netcentric/cn-website/issues/177 ?

**Comment by mhaack** [comment]
Hm, no. #177 is only to implement the forms on these pages. But some campaign pages had simpler, no standard header & footer, as confirmed by Katrin. This is what this ticket is about.
