### ISSUE TITLE
Missing image "alt" on header icon

### ISSUE THREAD

**Issue by mhaack** [Netcentric/cn-website#191]

**Comment by NCalexiaeche** [comment]
Can you please investigate if this is still happening @EduNCgit ?

**Comment by EduNCgit** [comment]
Issue is still present. "alt" attribute is missing for the icon. 

<img width="546" alt="Screenshot 2023-01-12 at 16 04 10" src="https://user-images.githubusercontent.com/118289017/212087294-87ff8e6a-2df9-4ea1-90d4-ca53b7cb73fe.png">
