### ISSUE TITLE
Add "continue in english" popup for blog post links

### ISSUE THREAD

**Issue by mhaack** [Netcentric/cn-website#195]
All blogs displaying blog post teasers should be enhanced with the "continue in english" popup.

![Screenshot 2022-12-05 at 14 41 22 (2)](https://user-images.githubusercontent.com/2643450/205655157-d750777b-5eae-4f7a-9727-6d2af44217df.png)

This is a requirement for the Netcentirc DE site.

**Comment by jonatan-lledo-netcentric** [comment]
if the link doesn’t have an equivalent in DE version, it has to be shown every time the link it’s clicked

**Comment by NCalexiaeche** [comment]
Hi @EduNCgit can you check it respect this behavior please?

**Comment by EduNCgit** [comment]
I checked the behaviour. This popup is present on pages that don't have an equivalent in DE .

**Comment by EduNCgit** [comment]
But I just noticed, when opening the Blog from the footer links, the popup will show. But trying to open the Blog from the header menu dropdown, will just open a new page without any popup warning. Could this be an issue ? @mhaack 

![blogDE](https://user-images.githubusercontent.com/118289017/208409796-882df764-eaaf-4cec-842f-f7968358c8b4.png)

**Comment by NCalexiaeche** [comment]
The correct behavior should be:

- If the user is on the german version of the website
- If he tries to go to an english page (not translated page in german), the user should see the pop up
