### ISSUE TITLE
'Contact Us' button on 'What we do' page is not working

### ISSUE THREAD

**Issue by EduNCgit** [Netcentric/cn-website#206]
'Contact Us' button on 'What we do' page is not working. 
The button is present on image number 6 - Find Out More.

As Jonatan explained me on Slack : "The href link goes to a placeholder link, so it goes to the same page" 
So it needs to be fixed. 

Link : https://main--netcentric--hlxsites.hlx.live/what-we-do

Screenshot : 
<img width="1183" alt="contactusbutton" src="https://user-images.githubusercontent.com/118289017/206163063-3cba8c2b-14ba-46c8-9456-42182080da16.png">

**Comment by jonatan-lledo-netcentric** [comment]
Thanks to Katrin Weissenborn the button link has been updated, so this issue can be closed
