### ISSUE TITLE
Language switch highlighting

### ISSUE THREAD

**Issue by nc-andreashaller** [Netcentric/cn-website#212]
On the DE branch also the "EN" link is highlighted: https://main--cn-website--netcentric.hlx.live/de

![image](https://user-images.githubusercontent.com/20042674/207259743-d0e6a606-5e26-447a-9f2c-7b21185fbb66.png)

**Comment by joanbeltran** [comment]
Also the lang attribute in the html tag is still "en"

**Comment by NCalexiaeche** [comment]
I gues @joanbeltran you can take this one together with the header/footer translation
