### ISSUE TITLE
Translate German header and footer

### ISSUE THREAD

**Issue by nc-andreashaller** [Netcentric/cn-website#213]
header and footer are not part of the automated import, they need to be translated manually, the english version was already copied to the /de folder

- https://docs.google.com/document/d/1aM48KOFF5yQxuo-PKYDc1XG1oM53sq9fHH-28O1aEas/edit
- https://docs.google.com/document/d/1iUipQsRiVw3sb7m2q6XjdNuwNLKXRt4uJyJcpFDJ598/edit

**Comment by joanbeltran** [comment]
Done

**Comment by joanbeltran** [comment]
Translated nav and footer manually
