### ISSUE TITLE
Blog Page Template elements not shown 

### ISSUE THREAD

**Issue by eduardGorpasin** [Netcentric/cn-website#219]
We have created recently several blogs in this path: https://drive.google.com/drive/folders/16BIdYd7XhHk_ATQbEun9N06e__LsUUMl

One blog does not show the elements that make up the blog page template. The page in question is this one: https://main--netcentric--hlxsites.hlx.page/insights/2022/12/accessible-websites-why-we-often-fail-and-how-to-improve 
The following elements are missing:

- just under the blog image and to the right: author profile, date, and sharing button(s).
- at the bottom of the page after the _Get in touch to learn more button_:  Topics component & author profile

Please investigate and address this issue.

**Comment by mhaack** [comment]
@eduardGorpasin fixed, the issue was in the content meta data for author name is `Authors` but was `Author`. The name of the meta attribute has to stay the same, in depended of one or multiple authors.

**Comment by NCalexiaeche** [comment]
@eduardGorpasin can you please confirm that is fixed & close it please?

**Comment by NCalexiaeche** [comment]
The page doesn't exist anymore
