### ISSUE TITLE
Issue on the spotify embeds

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#228]
Hi, there is an issue on the spotify embeds on some browsers, like on Safari
https://main--netcentric--hlxsites.hlx.page/insights/netcentric-podcast 
<img width="1238" alt="Screenshot 2022-12-16 at 15 46 14" src="https://user-images.githubusercontent.com/120196152/208126322-1008e818-1bde-410d-a4bf-a9a47a5e84c2.png">

**Comment by mhaack** [comment]
Might a temporary issue on spotify side? The link works for me?
Also `502 Bad Gateway - nginx` is nothing from Franklin.

**Comment by EduNCgit** [comment]
This could have been a Spotify issue. I checked today and everything works fine
