### ISSUE TITLE
Set up content query index for the search functionality

### ISSUE THREAD

**Issue by AngelaFabregues** [Netcentric/cn-website#230]

**Comment by mhaack** [comment]
@AngelaFabregues why its that needed? We already have https://netcentric.biz/query-index.json which has the entire page.

**Comment by nc-andreashaller** [comment]
https://netcentric.biz/query-index.json does not have the entire page, it has only a few fields, we need the full text content for ingestion, we could add new fields to the existing index or just create a new one

**Comment by mhaack** [comment]
I see, yes I suggest to extend the current existing index config

**Comment by nc-andreashaller** [comment]
Why extending instead of a dedicated one? those fields will be very search specific like "full text", "boosted" etc. with just all text content in it. I don't see why we should clutter the existing index with those values, will only bloat the payload for other usages.

**Comment by mhaack** [comment]
`query-index.json` already has all pages, only fields are missing, if I understood it correctly? So why not just adding them instead of a second index config to index the same amount of pages.

Technically both approaches are fine. Maybe this is just personal preference.

**Comment by nc-andreashaller** [comment]
exactly, all pages but not all content, my preference would be separate because the content is quite specific for search and I don't see any other consumer interested in those values, it will bloat the payload for others.

**Comment by AngelaFabregues** [comment]
Hi @mhaack ,
it is necessary for the search functionality only.
Thanks @nc-andreashaller .
