### ISSUE TITLE
Cleanup Marketo Code

### ISSUE THREAD

**Issue by nc-andreashaller** [Netcentric/cn-website#241]
CSS: https://github.com/Netcentric/cn-website/blob/main/blocks/form/form-marketo.css
JS: https://github.com/Netcentric/cn-website/blob/main/blocks/form/form.js

Both should be cleaned up. Unfortunately we cannot easily change classes from the generated Marketo form but at least it should be looked over if it can be optimised.

**Comment by NCalexiaeche** [comment]
@nc-andreashaller can you please add some more guidelines here about the clean up so @jonatan-lledo-netcentric can start looking at it please?
