### ISSUE TITLE
Forms broken (Webinar)

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#243]
Identify the issue on webinar where the form is broken :
https://www.netcentric.biz/library/future-of-customer-experience

@EduNCgit Check if it happens on other pages

**Comment by EduNCgit** [comment]
I checked different pages that contain forms, I didn't find any issues present. 
The page linked above is the only one affected.

**Comment by jonatan-lledo-netcentric** [comment]
It was a content issue. I moved the market form (the link) outside the column block and now is working. No more code needed
