### ISSUE TITLE
Oversized images

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#244]
Images are oversized on most of pages, can we identify those pages & downsize them

**Comment by NCalexiaeche** [comment]
example here: https://www.netcentric.biz/library/future-of-customer-experience

**Comment by NCalexiaeche** [comment]
@EduNCgit let's try to reimport the images from AEM without editing it, except from reducing the size within the google doc & let's confirm we can move ahead with this solution please

**Comment by EduNCgit** [comment]
Closing as a new issue https://github.com/Netcentric/cn-website/issues/256 was created for better explanation
