### ISSUE TITLE
Marketo Form cannot be embedded in the page template structure

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#255]
#https://github.com/Netcentric/cn-website/issues/243
When a form need to be embedded into a column then the marketo form does not work.
So if the marketing team need to make it appear on a side of the website, this is not possible currently.

**Comment by NCalexiaeche** [comment]
![Screenshot 2023-01-12 at 17 51 40](https://user-images.githubusercontent.com/120196152/212129762-f21efca0-0144-4bce-9d87-b3b5ef1689fd.png)

**Comment by nc-andreashaller** [comment]
Generally Franklin does not support nested blocks, there are some options how we could solve this:

- we could support auto block form only
- we could have a second way to do columns using section "magic" with section metadata
- we could add some metadata to the form itself to tell JS to put it in the previous column
- we could just live with the limitation of Franklin to not being able to nest blocks ...

I've organised a meeting to discuss it and will update this ticket

**Comment by nc-andreashaller** [comment]
After internal discussion we agreed on the following implementation:

- the page should get a template "two-column" assigned in the metadata
- if the template is set our code should show the **first** and **second** section of the document side-by-side as two columns
- the width of the columns should be adjustable by section metadata
- for applying the template please have a look at https://github.com/Netcentric/cn-website/blob/main/scripts/scripts.js#L234-L249 and https://github.com/Netcentric/cn-website/blob/main/templates/blogpost/blogpost.js#L3-L12

**Comment by NCalexiaeche** [comment]
@jonatan-lledo-netcentric to prioritize this one please
