### ISSUE TITLE
Resizing an image in Google Docs doesn't work

### ISSUE THREAD

**Issue by EduNCgit** [Netcentric/cn-website#256]
For the webinars pages (but not only) we need to download high quality images from AEM , upload them in Google Docs and resize using the tools available in Docs in order to reduce the size to normal without compromising quality. 
But after resizing and previewing/publishing the page, the image remains oversized.

Example : 
Image resized in docs : https://docs.google.com/document/d/13fu6ecGMJXouIrQQAhc6p2aPLK8GcIzsNeA8WTrJ50Q/edit#heading=h.fjyk4tk2qg88
Image present on site : https://www.netcentric.biz/library/future-of-customer-experience

<img width="375" alt="Screenshot 2023-01-13 at 16 24 06" src="https://user-images.githubusercontent.com/118289017/212342888-a45cc104-d92d-4e50-ba2c-4b43fb6b1ddc.png">
<img width="659" alt="Screenshot 2023-01-13 at 16 24 12" src="https://user-images.githubusercontent.com/118289017/212342899-ecef843d-3908-481a-8243-bf3b2799d4b0.png">

**Comment by nc-andreashaller** [comment]
If smaller images need to be used within a column (not spanning the whole column width) they need to be resized to the wished size outside of Franklin (for example in the MacOS preview) for giving the option to show images smaller with text on the right we'll add another option to the column block for a 15-85 ratio and an additional option to reduce/remove the gap between columns
