### ISSUE TITLE
Implement `server-timing` headers to track CDN caching

### ISSUE THREAD

**Issue by verlok-cn** [Netcentric/cn-website#276]
**Scenario**

As a web performance consultant, I'd like to be able to track whether or not a page was returned from the CDN, so that I would be able to a) split web performance data depending on CDN-cached or not-CDN-cached. b) spot current or future problems due to CDN caching.

**Request**

The request is to send `server-timing` headers along with the network response.

I know here we don't use Cloudfront, but here's how we did that on Cloudfront, for reference:

```js
function handler(event) {
    var response = event.response;
    if (response.headers.hasOwnProperty("age")){
        var age = response.headers.age.value;
        if (age > 0){
            response.headers["server-timing"] = {value: "cdn-cache;dur="+ age};
        }
    }
    return response;
}
```

Would it be possible to do the same on the Cognizant Netcentric website's CDN?

**Slack conversation reference**

Ref: [Slack conversation](https://ncchat.slack.com/archives/C03K480JSF4/p1674135813544049)

**Comment by nc-andreashaller** [comment]
Header set in discussed in https://ncchat.slack.com/archives/C02J4CACE3C/p1676542767916659:

Example:

> server-timing: time-start-msec;dur=1676573893671,time-elapsed;dur=96,fastly-pop;desc=FRA,hit-state;desc=PASS,age;dur=0.000,be-hit-state;desc=MISS|HIT|MISS|MISS
