### ISSUE TITLE
GDPR Recruiting Form

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#283]
Frontend of Employee GDPR form need to be updated accordingly:
https://www.netcentric.biz/legal/gdpr/confirmation.html 
using the new API implemented for GDPR to send the result of the acceptation in [this ticket](https://github.com/Netcentric/cn-website/issues/181), [documented  #here.](https://projects.netcentric.biz/wiki/display/NCWEB/NC+API+GDPR)

**Comment by nc-andreashaller** [comment]
CDN needs to be updated to bring the form/process live.
