### ISSUE TITLE
Test UX on Mobile 

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#301]
Test UX on Mobile as we are seeing some issues:

- Search box disappear on the hamburger menu on some Android phone

**Comment by nehakama** [comment]
please provide the list for devices to conduct the test.

**Comment by NCalexiaeche** [comment]
Please test with the 3-4 latest iphone & Samsung devices.

**Comment by nehakama** [comment]
List :
ios
 phones: iphone14, 14 pro
 : iapd 10'th

andriod 
phones: S23, 23 altra
tab : S8

**Comment by chriscorr1** [comment]
Maybe this one is connected with the following raise Bug?

 [BUG: samsung Tab UI: search bar is not appearing at the bottom of the menu#312](https://github.com/Netcentric/cn-website/issues/312)

**Comment by alexnerdrumhansen** [comment]
Tested on:
Samsung Galaxy S23/22/21
Pixel 8/7/6 Pro
iPhone 14/15

Tablets show the search bar at the bottom of burger menu (iPad 9th gen and Samsung Tab 8).

No long appear to be a bug so closing.
