### ISSUE TITLE
Replace jobfeed page by temporary not available page

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#302]
HR are cancelling the contract with SmartRecruiters who are populating our jobs on the careers page. The new contract with the new provider is still not finalised hence we might be losing the jobs visibility. They would like to post a message that we are working on bringing the jobs back or something. It is likely to stop on Monday.

**Comment by nc-andreashaller** [comment]
This can be done by a content change. Just put whatever message/content which makes sense on the job page.

**Comment by nc-andreashaller** [comment]
@NCalexiaeche I added a new placeholder to https://docs.google.com/spreadsheets/d/1fhhdEIYdL1HAqN8Ehto4obh4UF_Tv8SbGTz9t75Qzpk/edit#gid=0 please make sure the text is aligned with marketing:
![image](https://user-images.githubusercontent.com/20042674/225037650-d1dc9162-ba23-43d3-b316-0cf4acd474e3.png)
