### ISSUE TITLE
Stress Test for summit prep on high traffic to test search perf

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#307]
Purpose:
The idea is to perform Stress Test to simulate high traffic like for the upcoming summit, testing search performance, etc so we can leverage an additional node ahead.

**Comment by nehakama** [comment]
Using Jmter for load test

**Comment by nehakama** [comment]
I  tried the load test  with 500 users and  script executed without any error.

**Comment by nehakama** [comment]
![load-result](https://user-images.githubusercontent.com/129032537/228210512-f5d4ec28-21de-4585-a28b-7295d347b12e.jpg)
