### ISSUE TITLE
Fix Whitepaper broken form

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#314]
We need to make sure the following is working:
User fills out the form to receive the whitepaper --> this triggers one email that includes the whitepaper link for download and it is what the user actually wants.

Although in those below URLS when the white papers forms is being filled by the user, the user is not getting this link sent by email :
https://www.netcentric.biz/library/ncwhitepaper-raiffeisen.html
https://www.netcentric.biz/library/ncwhitepaper-maximizing-digital-platform-returns.html
https://www.netcentric.biz/library/ncwhitepaper-upgrading-marketing-operations.html
https://www.netcentric.biz/library/ncwhitepaper-actioning-automation.html
https://www.netcentric.biz/library/ncwhitepaper-aep.html
https://www.netcentric.biz/library/ncwhitepaper-content-velocity.html
https://www.netcentric.biz/library/ncwhitepapers-cutting-complexity.html
https://www.netcentric.biz/library/ncwhitepapers-automotive-innovation.html
https://www.netcentric.biz/library/ncwhitepapers-financial-services.html
https://www.netcentric.biz/library/ncwhitepapers-health-life-sciences.html
https://www.netcentric.biz/library/ncwebinars-content-velocity.html
It should have some copy like 'Here is your whitepaper [name of the whitepaper] and a link to download the whitepaper as pdf. So this is the email the user actually wants and it is not sent.

The only thing that is currently working fine right now is the following: 
In addition to the whitepaper form filling, the client can click the checkbox 'Sign up to access the latest news and discover your next digital solution.' = user signs up for our newsletter. 
--> This triggers a second email that confirms the person successfully signed up for the newsletter which is working fine right now & should remain like this.

**Comment by NCalexiaeche** [comment]
Here is the complete list of whitepapers urls & forms to be checked:
https://www.netcentric.biz/library/ncwhitepaper-raiffeisen.html
https://www.netcentric.biz/de/library/ncwhitepaper-raiffeisen.html
https://www.netcentric.biz/library/ncwhitepaper-maximizing-digital-platform-returns.html
https://www.netcentric.biz/library/ncwhitepaper-upgrading-marketing-operations.html
https://www.netcentric.biz/library/ncwhitepaper-actioning-automation.html
https://www.netcentric.biz/library/ncwhitepaper-aep.html
https://www.netcentric.biz/library/ncwhitepaper-content-velocity.html
https://www.netcentric.biz/library/ncwhitepapers-cutting-complexity.html
https://www.netcentric.biz/library/ncwhitepapers-automotive-innovation.html
https://www.netcentric.biz/library/ncwhitepapers-financial-services.html
https://www.netcentric.biz/library/ncwhitepapers-health-life-sciences.html
https://www.netcentric.biz/library/ncwhitepapers-designing-for-uncertainty.html
https://www.netcentric.biz/library/ncwhitepapers-dde.html
https://www.netcentric.biz/de/library/ncwhitepaper-content-velocity.html
https://www.netcentric.biz/de/library/ncwhitepaper-aep.html
https://www.netcentric.biz/de/library/ncwhitepaper-upgrading-marketing-operations.html
https://www.netcentric.biz/de/library/ncwhitepaper-actioning-automation.html
https://www.netcentric.biz/de/library/ncwhitepapers-cutting-complexity.html
https://www.netcentric.biz/de/library/ncwhitepaper-maximizing-digital-platform-returns.html
https://www.netcentric.biz/de/library/ncwhitepapers-automotive-innovation.html
https://www.netcentric.biz/de/library/ncwhitepapers-financial-services.html
https://www.netcentric.biz/de/library/ncwhitepapers-health-life-sciences.html
https://www.netcentric.biz/de/library/ncwhitepapers-designing-for-uncertainty.html
https://www.netcentric.biz/de/library/ncwhitepapers-dde.html

Can you please check all of them Neha ?

**Comment by nehakama** [comment]
Tested all the above llinks and prepared excel file with the emails received yes/no

**Comment by nehakama** [comment]
[NC-email_links.xlsx](https://github.com/Netcentric/cn-website/files/11309411/NC-email_links.xlsx)

**Comment by NCalexiaeche** [comment]
@alexnerdrumhansen can you check this one please? https://expertise.netcentric.biz/de/interactivewp-health-life-sciences

**Comment by alexnerdrumhansen** [comment]
I’m getting the email for https://www.netcentric.biz/de/library/ncwhitepapers-dde, but it’s not the correct one 
Katrin mentioned should be sent out.
As for https://expertise.netcentric.biz/de/interactivewp-health-life-sciences#pre-content there’s currently no form on the page as far as I can locate. That’s fine like that for now right?
