### ISSUE TITLE
oversized padding for embed Component

### ISSUE THREAD

**Issue by DaphneKoren** [Netcentric/cn-website#320]
**Tested page URL:**  
Experience is embedded here: 
https://www.netcentric.biz/what-we-do
https://www.netcentric.biz/de/what-we-do

 **Steps to Reproduce:** 
Go to the pages above and check the padding for the class="block embed embed-offerings embed-is-loaded" padding.

**Expected Result:**
Top padding is 32px L-XL 28.8px M 25.6px  S

* Optional solution suggested by Jonatan:
Make the padding editable by the authors 

**Actual Result:**  
65%
Screenshot attached √

**Code**
Found in embed.js

const embedOfferings = (url) => {
  const embedHTML = `<div style="left: 0; width: 100%; height: 0; position: relative; padding: 65% 0;">
    <iframe src="${url.href}" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute; overflow: visible;" allowfullscreen=""
      scrolling="yes" allow="encrypted-media" title="Content from ${url.hostname}" loading="lazy">
    </ifram
<img width="1648" alt="Screenshot 2023-04-11 at 14 46 41" src="https://user-images.githubusercontent.com/129506609/231180763-a4705881-ec14-482b-8a9b-0a70980345f9.png">
e>
  </div>`;

**Comment by alexnerdrumhansen** [comment]
Checked in Chrome after alignment with Sonald and Daphne. Looks good in small, medium and large viewports.

**Comment by alexnerdrumhansen** [comment]
Checked again on:
https://www.netcentric.biz/what-we-do
https://www.netcentric.biz/de/what-we-do

Both look fine now in small, medium, large and x-large sizes.
