### ISSUE TITLE
Implement a dedicated block to have a grey filter on the image

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#321]

**Comment by DaphneKoren** [comment]
Related to https://github.com/Netcentric/cn-website/issues/285
Blocks can be found - https://www.netcentric.biz/our-industries 
and 
https://www.netcentric.biz/how-we-work

**Comment by DaphneKoren** [comment]
<img width="1067" alt="Screenshot 2023-04-13 at 12 29 10" src="https://user-images.githubusercontent.com/129506609/231732302-d7b6031e-20ee-45e1-baf4-fefca839cbb1.png">
<img width="998" alt="Screenshot 2023-04-13 at 12 29 19" src="https://user-images.githubusercontent.com/129506609/231732331-d91611ae-fca8-48a4-9816-e2a57bc29061.png">
This seems fixed 
screenshots attached 
https://www.netcentric.biz/our-industries
and
https://www.netcentric.biz/how-we-work
https://www.netcentric.biz/careers/netcentric-academy


<img width="985" alt="Screenshot 2023-04-13 at 12 29 02" src="https://user-images.githubusercontent.com/129506609/231732367-b331ab0a-3a04-4f4c-9679-51a4b08b0dba.png">
