### ISSUE TITLE
Implement colors from the brand guidelines to "Side by side card" with solid color

### ISSUE THREAD

**Issue by DaphneKoren** [Netcentric/cn-website#323]
More info can be found in  https://github.com/Netcentric/cn-website/issues/285

**Expected results**
https://www.figma.com/file/OeE1zEoK84ckQpsAVMP6Ps/Modifications-(Copy)?node-id=1039-13365&t=Ov0N3Sc0yBTopEfr-0

**URLs**
 in https://www.netcentric.biz/
![225551041-0260c311-74d3-4c0c-9ef8-2b645d1c0776](https://user-images.githubusercontent.com/129506609/232003580-c93bb171-9d59-4960-af75-0db3058e75e9.png)

https://www.netcentric.biz/our-industries/automotive

**Comment by NCalexiaeche** [comment]
This should be a separated component from the image grey filter overlay.
Is it possible to copy that component & make change on this new one to fit this ticket need on the solid color?

**Comment by NCalexiaeche** [comment]
@sonaldhekale please provide guidelines for @alexnerdrumhansen to test it, can you create 2 test pages for that purpose with and without the block features to handle proper testing.

**Comment by sonaldhekale** [comment]
hi @alexnerdrumhansen you can check here https://323-implement-solid-colors--cn-website--netcentric.hlx.page/drafts/ahaller/cards-solid-colors

**Comment by nc-andreashaller** [comment]
@sonaldhekale please clean up the PR as discussed so the tests happen with the "final" code version.

**Comment by sonaldhekale** [comment]
PR is cleaned @alexnerdrumhansen you can test on https://323-implement-solid-colors--cn-website--netcentric.hlx.page/drafts/sdhekale/cards-solidcolors

**Comment by nc-andreashaller** [comment]
We can merge the PR as soon as Alex gives the QA "go".

**Comment by alexnerdrumhansen** [comment]
The Teal colour should still be replaced by the Midnight Blue as seen here: https://www.figma.com/file/OeE1zEoK84ckQpsAVMP6Ps/Modifications-(Copy)?type=design&node-id=1060-13437&t=e5Pt6puL43AZNAUw-0 (Frame 17).

**Comment by DaphneKoren** [comment]
![Screenshot 2023-05-25 at 11 33 19](https://github.com/Netcentric/cn-website/assets/129506609/8b23d77c-ff05-49f1-bc9f-2e8e71c48711)
Solid colour issue is fixed
