### ISSUE TITLE
Adding block option to Leader profile block 

### ISSUE THREAD

**Issue by DaphneKoren** [Netcentric/cn-website#326]
Content guidelines:

- Make sure Author crops images to square to prevent the image getting pinched in the flyout
- Text should not be longer than one line - should be restricted in content guidelines 
-  Download button will truncate with ellipsis if longer than allotted space

AC:

1. Create a Block option for the existing block ( Leader Profiles) so it displays 2 columns and uses the full width of the main grid
2.  Text under the image should be in black size 26px
3. Block should have the option to have the under image text convert to a button 
4. Able to add an ordered list
5. Add the option to add a button in the flyout ([Block 5 - 8 Images mosaic with title tag*](https://projects.netcentric.biz/wiki/pages/viewpage.action?pageId=430092249))
6. The whole block (image and text) is clickable and opens the flyout

Specs:
[Block 1- Leader Profiles new Block option](https://projects.netcentric.biz/wiki/display/NCWEB/Block+1-+Leader+Profiles+new+Block+option?src=contextnavpagetreemode)
https://projects.netcentric.biz/wiki/pages/viewpage.action?pageId=430092249

Example: 
![Screenshot 2023-04-24 at 13 14 06](https://user-images.githubusercontent.com/129506609/234585431-a120643e-d949-43a9-a547-17e1a5510557.png)

**Comment by nc-andreashaller** [comment]
@sonaldhekale if I get this ticket correctly the 2 column layout should be just an option and not all instances of this block should have that layout, please align with @DaphneKoren if https://326-flavour-to-leader-profile--cn-website--netcentric.hlx.page/who-we-are is really what is needed.

**Comment by DaphneKoren** [comment]
@sonaldhekale Yes, @nc-andreashaller is correct this should be a as a flavour to allow both the old design and this design according to the author's decision

**Comment by nc-andreashaller** [comment]
Did you specify how the author selects the design?

**Comment by DaphneKoren** [comment]
I updated the ticket and specs with the correct terminology

**Comment by nc-andreashaller** [comment]
Thanks! @sonaldhekale the "flavour" should be done by a so called "Block Option" which refers to the additional CSS class after the block name in parenthesis.

**Comment by sonaldhekale** [comment]
All things are clear now i did the the changes. PR is created it required review to move to testing.Thanks
