### ISSUE TITLE
Block 2  - Flip cards 

### ISSUE THREAD

**Issue by DaphneKoren** [Netcentric/cn-website#327]
**User story:**
As a user I would like to be able to add flip cards so that I can display cards with an interactive animation

This block is created to provide a replacement for the ION component seen in [content-at-scale-offering](https://expertise.netcentric.biz/content-at-scale-offering)

**AC:**

- Each card has a title + pre-title, and a text 
- Each card has a hover event
- Pre-title and title appear on both the active(expanded) and default view
- Colour of card background default status is different from the hover effect
- Each card has a different colour
- Hover state card has a  border 1 px 
- Hover state text colour different to default state text colour
- Text allows lists, links and Bold/underline/cursive design
- Pre-title and title are left aligned 
- When the item is in focus the section expands with animation
- Limited number of lines according to design
- Number of cards is always even 
- Min of 2 cards 

**Specs:**
[Block 2- Flip cards with hover effect](https://projects.netcentric.biz/wiki/display/NCWEB/Block+2-+Flip+cards+with+hover+effect?src=contextnavpagetreemode)
Colour guidelines: [Accessibility colour recommendation](https://projects.netcentric.biz/wiki/display/NCWEB/Accessibility+colour+recommendation?src=contextnavpagetreemode)

**Comment by NCalexiaeche** [comment]
@mihai-buricea-net can you please double check the specs with @Gonzalo-CG ? Maybe check the colours of the link plus background colour with Joel for the design

**Comment by Gonzalo-CG** [comment]
After reviewing the colors with Joel, it was decided that links on the Flip Card should be black (#000) and underlined, and change color to Dark Teal (#06C7CC) on hover. I've added this to the [Design part of the specs](https://projects.netcentric.biz/wiki/display/NCWEB/Block+2-+Flip+cards+with+hover+effect#Block2Flipcardswithhovereffect-Design)

**Comment by alexnerdrumhansen** [comment]
Tested and commented https://github.com/Netcentric/cn-website/pull/342
