### ISSUE TITLE
Block 6 - Multicolour Accordion

### ISSUE THREAD

**Issue by DaphneKoren** [Netcentric/cn-website#329]
**User story:** 
As a user I would like to be able add an accordion to display content in an expanding colourful block
This block is created to replace the accordion component from ION seen in [/diversity-testimonials](https://expertise.netcentric.biz/diversity-testimonials)

**AC:**

- Accordion with alternating item colours
- Each item has a Details/Close button with hover effect
- The first line of the content line is the item title and displayed when closed
- From the second line onwards the text entered will be the item drop down content  
- Closed and open item background is the same 
- There is a white separator between items 
- Details on hover and Close button have the same design
- Content can have links, unordered list,  bold, italic underline and ordered list
- Link in content opens in new tab
- Block has current design in specs [Block 6 Accordion alternating colour](https://projects.netcentric.biz/wiki/display/NCWEB/Block+6+Accordion+alternating+colour?src=contextnavpagetreemode)
- Can only open one accordion item at a time, previous opened item will close
- Accordion has a minimum of 2 items
- Accordion has a Max of 8 items

**Specs:**
[Block 6 Accordion alternating colour](https://projects.netcentric.biz/wiki/display/NCWEB/Block+6+Accordion+alternating+colour?src=contextnavpagetreemode)

Colours : [Accessibility colour recommendation](https://projects.netcentric.biz/wiki/display/NCWEB/Accessibility+colour+recommendation?src=contextnavpagetreemode)

**Example from ION:**
current page https://www.netcentric.biz/cognizant-netcentric-summit

**Comment by alexnerdrumhansen** [comment]
Tested. Looks good now on Desktop and Mobile. Screenshots in pull request.
