### ISSUE TITLE
Integrate Manatal Job portal embed

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#330]
AC:
HR / Talent Management need to migrate https://www.netcentric.biz/jobs from Smartrecruiters to Manatal #manatal-jira-integration-extravaganza 
The Manatal API need to be embeded so we can display the job offers as it is done today from Smartrecuiters platform

**Comment by DaphneKoren** [comment]
Specs: https://projects.netcentric.biz/wiki/display/NCWEB/Imbed+Manatal+API+to+replace+Smartrecruiters

**Comment by NCalexiaeche** [comment]
@biljana-popovic can you reach out to @DaphneKoren please?

**Comment by DaphneKoren** [comment]
New and improved spces: https://projects.netcentric.biz/wiki/display/NCWEB/Manatal+Iframe+integration

**Comment by NCalexiaeche** [comment]
Working on API, need to clean the code before PR and probably access to edit the Content, will probably need to do that.

**Comment by NCalexiaeche** [comment]
https://330-integrate-manatal-job-portal-embed--cn-website--netcentric.hlx.page/jobs

**Comment by NCalexiaeche** [comment]
Waiting for Manatal for removing header & fixing wider & free purple space
