### ISSUE TITLE
Block 7- Spinning cards

### ISSUE THREAD

**Issue by DaphneKoren** [Netcentric/cn-website#334]
**User story:**
As a user I want to be able to create spinning cards so that they can display the content in an interactive way

**AC:**

- Each card display an image Title subtitle in default state
- Each card displays content when hovered(desktop) or tapped(mobile)
- Each card has the current design [Block 7- Spinning cards](https://projects.netcentric.biz/wiki/display/NCWEB/Block+7-+Spinning+cards?src=contextnavpagetreemode)
- The block displays a Min number of cards 1
- The block displays a Max number of cards 3
- Image must be square to not pinch n the circle 
- Text /title /subtitle must not over extend allowed space 

**More info:**
the block is created to replace the ion content 
Current page 
https://www.netcentric.biz/how-we-work/sales/cognizant-netcentric-sales-events-oslo
ion link https://expertise.netcentric.biz/speakers_cph

**Specification:**
[Block 7- Spinning cards](https://projects.netcentric.biz/wiki/display/NCWEB/Block+7-+Spinning+cards?src=contextnavpagetreemode)

**Comment by alexnerdrumhansen** [comment]
Tested and looks good.
<img width="1634" alt="Screenshot 2023-07-31 at 12 06 04" src="https://github.com/Netcentric/cn-website/assets/131788856/7357ebca-aefe-489c-ba93-ae1fb424544d">
<img width="1633" alt="Screenshot 2023-07-31 at 12 06 11" src="https://github.com/Netcentric/cn-website/assets/131788856/922cef74-d37f-42f4-8465-f071a98ed14c">
<img width="877" alt="Screenshot 2023-07-31 at 12 06 36" src="https://github.com/Netcentric/cn-website/assets/131788856/7d8a839a-a034-4717-a59c-2b2c2e3b4c97">
<img width="879" alt="Screenshot 2023-07-31 at 12 06 47" src="https://github.com/Netcentric/cn-website/assets/131788856/0d721ec6-bac6-40aa-bfb9-3f5e75330b6f">
