### ISSUE TITLE
Block 8 Chapter cards

### ISSUE THREAD

**Issue by DaphneKoren** [Netcentric/cn-website#335]
User story:
As a user I want to be able to add the chapter cards so that i can display Chapter content 

AC:
- Each Chapter card is a link to another page 
- Each Chapter card display a title
- Each Chapter card displays a chapter name and number (i.e Chapter 1) in side a banner
- Each card has a button indicating weather the card can be opened + button or locked  Lock button
- min number of cards 2
- Max number of cards 3
- The cards have a hover effect
- The link of the chapter opens in the same page 
~~- The rest are locked~~
~~- Clicking a locked card opens a pop up~~
~~- The pop up  has a title a last name , first name, company, email fields and a submit button~~
~~- The pop up has an X close button~~
~~- When the pop up is showing the rest of the page has an overlay~~
~~- Clicking the X or the overlay closes the button~~
~~- Info entered in the pop up is saved securely~~
-  Length of chapter name should not exceed  available space 

** the locked card functionality was dropped after alignment w/ Marketing.

Each
Current page
https://expertise.netcentric.biz/interactivewp-health-life-sciences

Specification:
[Block 8 Chapter cards](https://projects.netcentric.biz/wiki/display/NCWEB/Block+8+Chapter+cards?src=contextnavpagetreemode)

**Comment by NCalexiaeche** [comment]
@Gonzalo-CG coordinatiing with marketing right now
