### ISSUE TITLE
Scrolleable iframe + page loading within the iframe

### ISSUE THREAD

**Issue by NCalexiaeche** [Netcentric/cn-website#343]
As of example: https://330-integrate-manatal-job-portal-embed--cn-website--netcentric.hlx.page/jobs

**Comment by NCalexiaeche** [comment]
@alexnerdrumhansen check other occurences of this behavior to be given examples to be fixed

**Comment by alexnerdrumhansen** [comment]
I've not had much luck finding another issue like it. Podcasts use iframe, but differently I believe so it's unlikely helpful for us.
