### ISSUE TITLE
DE: Homepage - Blog Overview button incorrect

### ISSUE THREAD

**Issue by alexnerdrumhansen** [Netcentric/cn-website#355]
Go to the Homepage https://www.netcentric.biz/de

Scroll down to Blogs and click the [BLOG ÜBERSICHT](https://www.netcentric.biz/insights) button. Notice it's both missing the /DE/ and /blog in the destination URL.

**Comment by alexnerdrumhansen** [comment]
Update, I can't find the button and how to change its link whilst editing the document/page.
Anyone in FE who knows if this is coming from the Related Blogs block?

**Comment by sonaldhekale** [comment]
I checked the button link is hard coded in code so we need to change it in code itself.

**Comment by alexnerdrumhansen** [comment]
Thank you @sonaldhekale , would you be able to look into making it configurable?

**Comment by sonaldhekale** [comment]
Yes sure i will work on this after finishing my current ticket.Thank you.
