### ISSUE TITLE
Spike - Franklin Sidekick Library

### ISSUE THREAD

**Issue by Gonzalo-CG** [Netcentric/cn-website#377]
### Business Value
As a content author, I want an easy and straightforward way to access all the blocks, icons, tags, etc. so that I can create content faster and in an easier way.

### Description
The outcome of this task will be an analysis, not an actual implementation. The implementation should be done on a follow-up ticket if PO decides to move forward.

### Acceptance Criteria
Dev team evaluates the implementation time and complexity of adding https://github.com/adobe/franklin-sidekick-library to the project.

**Comment by Victor-AcostaCNC** [comment]
I believe it would take a week to implement the Sidekick library with all the necessary plug-ins. It will try to do it in less time but, since it is the first time I work on such a task, I am calculating a week should be good.

**Comment by Gonzalo-CG** [comment]
Implementation will be done in #401.
