### ISSUE TITLE
BUG: Blog Post Page Sidebar - Multiple Authors Not Showing

### ISSUE THREAD

**Issue by Gonzalo-CG** [Netcentric/cn-website#383]
### Current Behavior
When more than 1 author is added to the "Authors" property of the Metadata block of a Blogpost template, the default author (Cognizant Netcentric) is shown on the rendered page's sidebar.

<img width="200" alt="image" src="https://github.com/Netcentric/cn-website/assets/139977780/b24e3a7c-c078-45d7-9da7-938b9988b5f3">

### Expected Behavior
When more than 1 author is present on the metadata block of a blogpost template, all the authors are shown on the rendered page's sidebar.

### Notes
Current behavior can be checked in the following draft [Blogpost template test](https://docs.google.com/document/d/1tC-Cs5PuewmOh7UYW8VmFDcMBxIaWvEKl_iqt1AqR08/edit)

**Comment by alexnerdrumhansen** [comment]
Tested and verified as fixed (see pull request).
